2021-12-02 16:56:21  INFO: HikariPool-1 - Starting...
2021-12-02 16:56:23  INFO: HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@18f8cd79
2021-12-02 16:56:23  INFO: HikariPool-1 - Start completed.
2021-12-02 16:56:24  INFO: Clearing database change log checksums
2021-12-02 16:56:24  INFO: Successfully acquired change log lock
2021-12-02 16:56:25  INFO: Successfully released change log lock
2021-12-02 16:56:25  INFO: Successfully acquired change log lock
2021-12-02 16:56:25  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.json.JsonChangeLogParser Unable to get public no-arg constructor
2021-12-02 16:56:25  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.yaml.YamlChangeLogParser Unable to get public no-arg constructor
2021-12-02 16:56:28  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-02 16:56:33  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-02 16:56:33  INFO: Cannot load service: liquibase.hub.HubService: Provider liquibase.hub.core.StandardHubService could not be instantiated
2021-12-02 16:56:33  INFO: Successfully released change log lock
2021-12-02 16:56:35  INFO: HikariPool-2 - Starting...
2021-12-02 16:56:35  INFO: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@5529ff44
2021-12-02 16:56:35  INFO: HikariPool-2 - Start completed.
2021-12-02 16:56:39  INFO: Operating system name: Linux version: 5.11.0-41-generic architecture: amd64
2021-12-02 16:56:39  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Ubuntu version: 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-02 16:56:39  INFO: Memory limit heap: 962mb non-heap: 0mb
2021-12-02 16:56:39  INFO: Character encoding: UTF-8 charset: UTF-8
2021-12-02 16:56:39  INFO: Version: 4.14
2021-12-02 16:56:39  INFO: Starting server...
2021-12-02 16:56:40  INFO: jetty-10.0.6; built: 2021-06-29T15:28:56.259Z; git: 37e7731b4b142a882d73974ff3bec78d621bd674; jvm 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-02 16:56:42  INFO: Started o.t.w.@751d7425{/,null,AVAILABLE}
2021-12-02 16:56:42  INFO: Session workerName=node0
2021-12-02 16:56:42  WARN: JAXBContext implementation could not be found. WADL feature is disabled.
2021-12-02 16:56:43  INFO: Started o.e.j.s.ServletContextHandler@ca2be53{/,null,AVAILABLE}
2021-12-02 16:56:43  INFO: Started ServerConnector@3b95d13c{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2021-12-02 16:56:43  INFO: Started Server@5657967b{STARTING}[10.0.6,sto=0] @25332ms
2021-12-02 19:32:59  INFO: HikariPool-1 - Starting...
2021-12-02 19:33:11 ERROR: HikariPool-1 - Exception during pool initialization. - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
2021-12-02 19:33:11 ERROR: Main method error - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
Exception in thread "main" java.lang.RuntimeException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at org.traccar.Main.run(Main.java:150)
	at org.traccar.Main.main(Main.java:108)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.traccar.database.DataManager.initDatabase(DataManager.java:131)
	at org.traccar.database.DataManager.<init>(DataManager.java:90)
	at org.traccar.Context.init(Context.java:319)
	at org.traccar.Main.run(Main.java:122)
	... 1 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:898)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	... 7 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:119)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:842)
	... 16 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
	... 18 more
2021-12-02 19:33:13  INFO: HikariPool-1 - Starting...
2021-12-02 19:33:18 ERROR: HikariPool-1 - Exception during pool initialization. - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
2021-12-02 19:33:18 ERROR: Main method error - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
Exception in thread "main" java.lang.RuntimeException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at org.traccar.Main.run(Main.java:150)
	at org.traccar.Main.main(Main.java:108)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.traccar.database.DataManager.initDatabase(DataManager.java:131)
	at org.traccar.database.DataManager.<init>(DataManager.java:90)
	at org.traccar.Context.init(Context.java:319)
	at org.traccar.Main.run(Main.java:122)
	... 1 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:898)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	... 7 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:119)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:842)
	... 16 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
	... 18 more
2021-12-02 19:33:21  INFO: HikariPool-1 - Starting...
2021-12-02 19:33:23  INFO: HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@7975d1d8
2021-12-02 19:33:23  INFO: HikariPool-1 - Start completed.
2021-12-02 19:33:28  INFO: Clearing database change log checksums
2021-12-02 19:33:30  INFO: Successfully acquired change log lock
2021-12-02 19:33:31  INFO: Successfully released change log lock
2021-12-02 19:33:32  INFO: Successfully acquired change log lock
2021-12-02 19:33:32  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.json.JsonChangeLogParser Unable to get public no-arg constructor
2021-12-02 19:33:32  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.yaml.YamlChangeLogParser Unable to get public no-arg constructor
2021-12-02 19:33:38  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-02 19:33:45  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-02 19:33:45  INFO: Cannot load service: liquibase.hub.HubService: Provider liquibase.hub.core.StandardHubService could not be instantiated
2021-12-02 19:33:45  INFO: Successfully released change log lock
2021-12-02 19:33:51  INFO: HikariPool-2 - Starting...
2021-12-02 19:33:51  INFO: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@4cc65c2
2021-12-02 19:33:51  INFO: HikariPool-2 - Start completed.
2021-12-02 19:33:52  INFO: Operating system name: Linux version: 5.11.0-41-generic architecture: amd64
2021-12-02 19:33:52  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Ubuntu version: 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-02 19:33:52  INFO: Memory limit heap: 962mb non-heap: 0mb
2021-12-02 19:33:52  INFO: Character encoding: UTF-8 charset: UTF-8
2021-12-02 19:33:52  INFO: Version: 4.14
2021-12-02 19:33:52  INFO: Starting server...
2021-12-02 19:33:53  INFO: jetty-10.0.6; built: 2021-06-29T15:28:56.259Z; git: 37e7731b4b142a882d73974ff3bec78d621bd674; jvm 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-02 19:33:54  INFO: Started o.t.w.@634e1b39{/,null,AVAILABLE}
2021-12-02 19:33:54  INFO: Session workerName=node0
2021-12-02 19:33:55  WARN: JAXBContext implementation could not be found. WADL feature is disabled.
2021-12-02 19:33:56  INFO: Started o.e.j.s.ServletContextHandler@cf08c97{/,null,AVAILABLE}
2021-12-02 19:33:56  INFO: Started ServerConnector@37864b77{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2021-12-02 19:33:56  INFO: Started Server@6c0b51da{STARTING}[10.0.6,sto=0] @35183ms
2021-12-02 19:48:31  INFO: HikariPool-1 - Starting...
2021-12-02 19:48:42  INFO: HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@2ad48653
2021-12-02 19:48:42  INFO: HikariPool-1 - Start completed.
2021-12-02 19:48:46  INFO: Clearing database change log checksums
2021-12-02 19:48:47  INFO: Successfully acquired change log lock
2021-12-02 19:48:49  INFO: Successfully released change log lock
2021-12-02 19:48:50  INFO: Successfully acquired change log lock
2021-12-02 19:48:50  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.json.JsonChangeLogParser Unable to get public no-arg constructor
2021-12-02 19:48:50  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.yaml.YamlChangeLogParser Unable to get public no-arg constructor
2021-12-02 19:48:58  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-02 19:49:06  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-02 19:49:06  INFO: Cannot load service: liquibase.hub.HubService: Provider liquibase.hub.core.StandardHubService could not be instantiated
2021-12-02 19:49:06  INFO: Successfully released change log lock
2021-12-02 19:49:18  INFO: HikariPool-2 - Starting...
2021-12-02 19:49:18  INFO: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@472d0f4
2021-12-02 19:49:18  INFO: HikariPool-2 - Start completed.
2021-12-02 19:49:21  INFO: Operating system name: Linux version: 5.11.0-41-generic architecture: amd64
2021-12-02 19:49:21  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Ubuntu version: 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-02 19:49:21  INFO: Memory limit heap: 962mb non-heap: 0mb
2021-12-02 19:49:21  INFO: Character encoding: UTF-8 charset: UTF-8
2021-12-02 19:49:21  INFO: Version: 4.14
2021-12-02 19:49:21  INFO: Starting server...
2021-12-02 19:49:22  INFO: jetty-10.0.6; built: 2021-06-29T15:28:56.259Z; git: 37e7731b4b142a882d73974ff3bec78d621bd674; jvm 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-02 19:49:23  INFO: Started o.t.w.@3404e5c4{/,null,AVAILABLE}
2021-12-02 19:49:24  INFO: Session workerName=node0
2021-12-02 19:49:26  WARN: JAXBContext implementation could not be found. WADL feature is disabled.
2021-12-02 19:49:27  INFO: Started o.e.j.s.ServletContextHandler@11adab6d{/,null,AVAILABLE}
2021-12-02 19:49:27  INFO: Started ServerConnector@87b5b49{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2021-12-02 19:49:27  INFO: Started Server@6222391a{STARTING}[10.0.6,sto=0] @93575ms
2021-12-03 16:03:26  INFO: HikariPool-1 - Starting...
2021-12-03 16:03:41 ERROR: HikariPool-1 - Exception during pool initialization. - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
2021-12-03 16:03:41 ERROR: Main method error - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
Exception in thread "main" java.lang.RuntimeException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at org.traccar.Main.run(Main.java:150)
	at org.traccar.Main.main(Main.java:108)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.traccar.database.DataManager.initDatabase(DataManager.java:131)
	at org.traccar.database.DataManager.<init>(DataManager.java:90)
	at org.traccar.Context.init(Context.java:319)
	at org.traccar.Main.run(Main.java:122)
	... 1 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:898)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	... 7 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:119)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:842)
	... 16 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
	... 18 more
2021-12-03 16:03:43  INFO: HikariPool-1 - Starting...
2021-12-03 16:03:47  INFO: HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@2ad48653
2021-12-03 16:03:47  INFO: HikariPool-1 - Start completed.
2021-12-03 16:03:49  INFO: Clearing database change log checksums
2021-12-03 16:03:52  INFO: Successfully acquired change log lock
2021-12-03 16:03:54  INFO: Successfully released change log lock
2021-12-03 16:03:54  INFO: Successfully acquired change log lock
2021-12-03 16:03:54  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.json.JsonChangeLogParser Unable to get public no-arg constructor
2021-12-03 16:03:55  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.yaml.YamlChangeLogParser Unable to get public no-arg constructor
2021-12-03 16:04:02  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-03 16:04:09  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-03 16:04:09  INFO: Cannot load service: liquibase.hub.HubService: Provider liquibase.hub.core.StandardHubService could not be instantiated
2021-12-03 16:04:09  INFO: Successfully released change log lock
2021-12-03 16:04:16  INFO: HikariPool-2 - Starting...
2021-12-03 16:04:17  INFO: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@472d0f4
2021-12-03 16:04:17  INFO: HikariPool-2 - Start completed.
2021-12-03 16:04:17  INFO: Operating system name: Linux version: 5.11.0-41-generic architecture: amd64
2021-12-03 16:04:17  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Ubuntu version: 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-03 16:04:17  INFO: Memory limit heap: 962mb non-heap: 0mb
2021-12-03 16:04:17  INFO: Character encoding: UTF-8 charset: UTF-8
2021-12-03 16:04:17  INFO: Version: 4.14
2021-12-03 16:04:17  INFO: Starting server...
2021-12-03 16:04:18  INFO: jetty-10.0.6; built: 2021-06-29T15:28:56.259Z; git: 37e7731b4b142a882d73974ff3bec78d621bd674; jvm 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-03 16:04:19  INFO: Started o.t.w.@3404e5c4{/,null,AVAILABLE}
2021-12-03 16:04:19  INFO: Session workerName=node0
2021-12-03 16:04:21  WARN: JAXBContext implementation could not be found. WADL feature is disabled.
2021-12-03 16:04:22  INFO: Started o.e.j.s.ServletContextHandler@11adab6d{/,null,AVAILABLE}
2021-12-03 16:04:22  INFO: Started ServerConnector@87b5b49{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2021-12-03 16:04:22  INFO: Started Server@6222391a{STARTING}[10.0.6,sto=0] @39532ms
2021-12-05 13:35:14  INFO: HikariPool-1 - Starting...
2021-12-05 13:35:30 ERROR: HikariPool-1 - Exception during pool initialization. - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
2021-12-05 13:35:30 ERROR: Main method error - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
Exception in thread "main" java.lang.RuntimeException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at org.traccar.Main.run(Main.java:150)
	at org.traccar.Main.main(Main.java:108)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.traccar.database.DataManager.initDatabase(DataManager.java:131)
	at org.traccar.database.DataManager.<init>(DataManager.java:90)
	at org.traccar.Context.init(Context.java:319)
	at org.traccar.Main.run(Main.java:122)
	... 1 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:898)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	... 7 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:119)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:842)
	... 16 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
	... 18 more
2021-12-05 13:35:32  INFO: HikariPool-1 - Starting...
2021-12-05 13:35:34  INFO: HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@2ad48653
2021-12-05 13:35:34  INFO: HikariPool-1 - Start completed.
2021-12-05 13:35:38  INFO: Clearing database change log checksums
2021-12-05 13:35:40  INFO: Successfully acquired change log lock
2021-12-05 13:35:41  INFO: Successfully released change log lock
2021-12-05 13:35:41  INFO: Successfully acquired change log lock
2021-12-05 13:35:41  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.json.JsonChangeLogParser Unable to get public no-arg constructor
2021-12-05 13:35:42  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.yaml.YamlChangeLogParser Unable to get public no-arg constructor
2021-12-05 13:35:46  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-05 13:35:53  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-05 13:35:53  INFO: Cannot load service: liquibase.hub.HubService: Provider liquibase.hub.core.StandardHubService could not be instantiated
2021-12-05 13:35:53  INFO: Successfully released change log lock
2021-12-05 13:36:00  INFO: HikariPool-2 - Starting...
2021-12-05 13:36:00  INFO: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@472d0f4
2021-12-05 13:36:00  INFO: HikariPool-2 - Start completed.
2021-12-05 13:36:01  INFO: Operating system name: Linux version: 5.11.0-41-generic architecture: amd64
2021-12-05 13:36:01  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Ubuntu version: 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-05 13:36:01  INFO: Memory limit heap: 962mb non-heap: 0mb
2021-12-05 13:36:01  INFO: Character encoding: UTF-8 charset: UTF-8
2021-12-05 13:36:01  INFO: Version: 4.14
2021-12-05 13:36:01  INFO: Starting server...
2021-12-05 13:36:02  INFO: jetty-10.0.6; built: 2021-06-29T15:28:56.259Z; git: 37e7731b4b142a882d73974ff3bec78d621bd674; jvm 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-05 13:36:03  INFO: Started o.t.w.@5bec3e0{/,null,AVAILABLE}
2021-12-05 13:36:03  INFO: Session workerName=node0
2021-12-05 13:36:04  WARN: JAXBContext implementation could not be found. WADL feature is disabled.
2021-12-05 13:36:05  INFO: Started o.e.j.s.ServletContextHandler@eb1d475{/,null,AVAILABLE}
2021-12-05 13:36:05  INFO: Started ServerConnector@87b5b49{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2021-12-05 13:36:05  INFO: Started Server@2dc39b53{STARTING}[10.0.6,sto=0] @33955ms
2021-12-06 11:05:57  INFO: HikariPool-1 - Starting...
2021-12-06 11:06:12 ERROR: HikariPool-1 - Exception during pool initialization. - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
2021-12-06 11:06:12 ERROR: Main method error - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
Exception in thread "main" java.lang.RuntimeException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at org.traccar.Main.run(Main.java:150)
	at org.traccar.Main.main(Main.java:108)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.traccar.database.DataManager.initDatabase(DataManager.java:131)
	at org.traccar.database.DataManager.<init>(DataManager.java:90)
	at org.traccar.Context.init(Context.java:319)
	at org.traccar.Main.run(Main.java:122)
	... 1 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:898)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	... 7 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:119)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:842)
	... 16 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
	... 18 more
2021-12-06 11:06:14  INFO: HikariPool-1 - Starting...
2021-12-06 11:06:19 ERROR: HikariPool-1 - Exception during pool initialization. - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
2021-12-06 11:06:19 ERROR: Main method error - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
Exception in thread "main" java.lang.RuntimeException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at org.traccar.Main.run(Main.java:150)
	at org.traccar.Main.main(Main.java:108)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.traccar.database.DataManager.initDatabase(DataManager.java:131)
	at org.traccar.database.DataManager.<init>(DataManager.java:90)
	at org.traccar.Context.init(Context.java:319)
	at org.traccar.Main.run(Main.java:122)
	... 1 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:898)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	... 7 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:119)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:842)
	... 16 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
	... 18 more
2021-12-06 11:06:22  INFO: HikariPool-1 - Starting...
2021-12-06 11:06:25  INFO: HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@1a5b6f42
2021-12-06 11:06:25  INFO: HikariPool-1 - Start completed.
2021-12-06 11:06:28  INFO: Clearing database change log checksums
2021-12-06 11:06:29  INFO: Successfully acquired change log lock
2021-12-06 11:06:31  INFO: Successfully released change log lock
2021-12-06 11:06:31  INFO: Successfully acquired change log lock
2021-12-06 11:06:31  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.json.JsonChangeLogParser Unable to get public no-arg constructor
2021-12-06 11:06:31  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.yaml.YamlChangeLogParser Unable to get public no-arg constructor
2021-12-06 11:06:34  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-06 11:06:40  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-06 11:06:40  INFO: Cannot load service: liquibase.hub.HubService: Provider liquibase.hub.core.StandardHubService could not be instantiated
2021-12-06 11:06:41  INFO: Successfully released change log lock
2021-12-06 11:06:47  INFO: HikariPool-2 - Starting...
2021-12-06 11:06:47  INFO: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@51e3d37e
2021-12-06 11:06:47  INFO: HikariPool-2 - Start completed.
2021-12-06 11:06:48  INFO: Operating system name: Linux version: 5.11.0-41-generic architecture: amd64
2021-12-06 11:06:48  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Ubuntu version: 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-06 11:06:48  INFO: Memory limit heap: 962mb non-heap: 0mb
2021-12-06 11:06:48  INFO: Character encoding: UTF-8 charset: UTF-8
2021-12-06 11:06:48  INFO: Version: 4.14
2021-12-06 11:06:48  INFO: Starting server...
2021-12-06 11:06:49  INFO: jetty-10.0.6; built: 2021-06-29T15:28:56.259Z; git: 37e7731b4b142a882d73974ff3bec78d621bd674; jvm 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-06 11:06:50  INFO: Started o.t.w.@5bec3e0{/,null,AVAILABLE}
2021-12-06 11:06:50  INFO: Session workerName=node0
2021-12-06 11:06:51  WARN: JAXBContext implementation could not be found. WADL feature is disabled.
2021-12-06 11:06:52  INFO: Started o.e.j.s.ServletContextHandler@eb1d475{/,null,AVAILABLE}
2021-12-06 11:06:52  INFO: Started ServerConnector@3fbfbf84{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2021-12-06 11:06:52  INFO: Started Server@2dc39b53{STARTING}[10.0.6,sto=0] @30396ms
2021-12-06 13:35:45  WARN: HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=48s589ms936µs496ns).
2021-12-06 13:35:45  WARN: HikariPool-2 - Thread starvation or clock leap detected (housekeeper delta=56s238ms353µs967ns).
2021-12-07 10:52:30  INFO: HikariPool-1 - Starting...
2021-12-07 10:52:46 ERROR: HikariPool-1 - Exception during pool initialization. - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
2021-12-07 10:52:46 ERROR: Main method error - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
Exception in thread "main" java.lang.RuntimeException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at org.traccar.Main.run(Main.java:150)
	at org.traccar.Main.main(Main.java:108)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.traccar.database.DataManager.initDatabase(DataManager.java:131)
	at org.traccar.database.DataManager.<init>(DataManager.java:90)
	at org.traccar.Context.init(Context.java:319)
	at org.traccar.Main.run(Main.java:122)
	... 1 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:898)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	... 7 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:119)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:842)
	... 16 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
	... 18 more
2021-12-07 10:52:48  INFO: HikariPool-1 - Starting...
2021-12-07 10:52:53 ERROR: HikariPool-1 - Exception during pool initialization. - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
2021-12-07 10:52:53 ERROR: Main method error - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
Exception in thread "main" java.lang.RuntimeException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at org.traccar.Main.run(Main.java:150)
	at org.traccar.Main.main(Main.java:108)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.traccar.database.DataManager.initDatabase(DataManager.java:131)
	at org.traccar.database.DataManager.<init>(DataManager.java:90)
	at org.traccar.Context.init(Context.java:319)
	at org.traccar.Main.run(Main.java:122)
	... 1 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:898)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	... 7 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:119)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:842)
	... 16 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
	... 18 more
2021-12-07 10:52:56  INFO: HikariPool-1 - Starting...
2021-12-07 10:52:58  INFO: HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@18f8cd79
2021-12-07 10:52:58  INFO: HikariPool-1 - Start completed.
2021-12-07 10:53:01  INFO: Clearing database change log checksums
2021-12-07 10:53:02  INFO: Successfully acquired change log lock
2021-12-07 10:53:04  INFO: Successfully released change log lock
2021-12-07 10:53:04  INFO: Successfully acquired change log lock
2021-12-07 10:53:04  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.json.JsonChangeLogParser Unable to get public no-arg constructor
2021-12-07 10:53:04  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.yaml.YamlChangeLogParser Unable to get public no-arg constructor
2021-12-07 10:53:07  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-07 10:53:14  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-07 10:53:14  INFO: Cannot load service: liquibase.hub.HubService: Provider liquibase.hub.core.StandardHubService could not be instantiated
2021-12-07 10:53:14  INFO: Successfully released change log lock
2021-12-07 10:53:21  INFO: HikariPool-2 - Starting...
2021-12-07 10:53:21  INFO: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@5529ff44
2021-12-07 10:53:21  INFO: HikariPool-2 - Start completed.
2021-12-07 10:53:22  INFO: Operating system name: Linux version: 5.11.0-41-generic architecture: amd64
2021-12-07 10:53:22  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Ubuntu version: 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-07 10:53:22  INFO: Memory limit heap: 962mb non-heap: 0mb
2021-12-07 10:53:22  INFO: Character encoding: UTF-8 charset: UTF-8
2021-12-07 10:53:22  INFO: Version: 4.14
2021-12-07 10:53:22  INFO: Starting server...
2021-12-07 10:53:23  INFO: jetty-10.0.6; built: 2021-06-29T15:28:56.259Z; git: 37e7731b4b142a882d73974ff3bec78d621bd674; jvm 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-07 10:53:24  INFO: Started o.t.w.@751d7425{/,null,AVAILABLE}
2021-12-07 10:53:24  INFO: Session workerName=node0
2021-12-07 10:53:26  WARN: JAXBContext implementation could not be found. WADL feature is disabled.
2021-12-07 10:53:26  INFO: Started o.e.j.s.ServletContextHandler@ca2be53{/,null,AVAILABLE}
2021-12-07 10:53:26  INFO: Started ServerConnector@3b95d13c{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2021-12-07 10:53:26  INFO: Started Server@5657967b{STARTING}[10.0.6,sto=0] @31268ms
2021-12-07 11:15:52  INFO: HikariPool-1 - Starting...
2021-12-07 11:16:04 ERROR: HikariPool-1 - Exception during pool initialization. - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
2021-12-07 11:16:04 ERROR: Main method error - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
Exception in thread "main" java.lang.RuntimeException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at org.traccar.Main.run(Main.java:150)
	at org.traccar.Main.main(Main.java:108)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.traccar.database.DataManager.initDatabase(DataManager.java:131)
	at org.traccar.database.DataManager.<init>(DataManager.java:90)
	at org.traccar.Context.init(Context.java:319)
	at org.traccar.Main.run(Main.java:122)
	... 1 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:898)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	... 7 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:119)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:842)
	... 16 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
	... 18 more
2021-12-07 11:16:06  INFO: HikariPool-1 - Starting...
2021-12-07 11:16:10  INFO: HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@28194a50
2021-12-07 11:16:10  INFO: HikariPool-1 - Start completed.
2021-12-07 11:16:13  INFO: Clearing database change log checksums
2021-12-07 11:16:16  INFO: Successfully acquired change log lock
2021-12-07 11:16:17  INFO: Successfully released change log lock
2021-12-07 11:16:18  INFO: Successfully acquired change log lock
2021-12-07 11:16:18  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.json.JsonChangeLogParser Unable to get public no-arg constructor
2021-12-07 11:16:18  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.yaml.YamlChangeLogParser Unable to get public no-arg constructor
2021-12-07 11:16:25  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-07 11:16:38  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-07 11:16:38  INFO: Cannot load service: liquibase.hub.HubService: Provider liquibase.hub.core.StandardHubService could not be instantiated
2021-12-07 11:16:38  INFO: Successfully released change log lock
2021-12-07 11:16:56  INFO: HikariPool-2 - Starting...
2021-12-07 11:16:56  INFO: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@3d620a1
2021-12-07 11:16:56  INFO: HikariPool-2 - Start completed.
2021-12-07 11:16:59  INFO: Operating system name: Linux version: 5.11.0-41-generic architecture: amd64
2021-12-07 11:16:59  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Ubuntu version: 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-07 11:16:59  INFO: Memory limit heap: 962mb non-heap: 0mb
2021-12-07 11:16:59  INFO: Character encoding: UTF-8 charset: UTF-8
2021-12-07 11:16:59  INFO: Version: 4.14
2021-12-07 11:16:59  INFO: Starting server...
2021-12-07 11:17:00  INFO: jetty-10.0.6; built: 2021-06-29T15:28:56.259Z; git: 37e7731b4b142a882d73974ff3bec78d621bd674; jvm 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-07 11:17:05  INFO: Started o.t.w.@62cf6a84{/,null,AVAILABLE}
2021-12-07 11:17:05  INFO: Session workerName=node0
2021-12-07 11:17:08  WARN: JAXBContext implementation could not be found. WADL feature is disabled.
2021-12-07 11:17:10  INFO: Started o.e.j.s.ServletContextHandler@70ee1963{/,null,AVAILABLE}
2021-12-07 11:17:10  INFO: Started ServerConnector@63716833{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2021-12-07 11:17:10  INFO: Started Server@3815146b{STARTING}[10.0.6,sto=0] @64459ms
2021-12-08 10:33:21  INFO: HikariPool-1 - Starting...
2021-12-08 10:33:35 ERROR: HikariPool-1 - Exception during pool initialization. - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
2021-12-08 10:33:35 ERROR: Main method error - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
Exception in thread "main" java.lang.RuntimeException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at org.traccar.Main.run(Main.java:150)
	at org.traccar.Main.main(Main.java:108)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.traccar.database.DataManager.initDatabase(DataManager.java:131)
	at org.traccar.database.DataManager.<init>(DataManager.java:90)
	at org.traccar.Context.init(Context.java:319)
	at org.traccar.Main.run(Main.java:122)
	... 1 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:898)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	... 7 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:119)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:842)
	... 16 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
	... 18 more
2021-12-08 10:33:37  INFO: HikariPool-1 - Starting...
2021-12-08 10:33:39  INFO: HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@7975d1d8
2021-12-08 10:33:39  INFO: HikariPool-1 - Start completed.
2021-12-08 10:33:41  INFO: Clearing database change log checksums
2021-12-08 10:33:43  INFO: Successfully acquired change log lock
2021-12-08 10:33:45  INFO: Successfully released change log lock
2021-12-08 10:33:46  INFO: Successfully acquired change log lock
2021-12-08 10:33:46  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.json.JsonChangeLogParser Unable to get public no-arg constructor
2021-12-08 10:33:46  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.yaml.YamlChangeLogParser Unable to get public no-arg constructor
2021-12-08 10:33:54  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-08 10:34:07  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-08 10:34:07  INFO: Cannot load service: liquibase.hub.HubService: Provider liquibase.hub.core.StandardHubService could not be instantiated
2021-12-08 10:34:08  INFO: Successfully released change log lock
2021-12-08 10:34:20  INFO: HikariPool-2 - Starting...
2021-12-08 10:34:20  INFO: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@4cc65c2
2021-12-08 10:34:20  INFO: HikariPool-2 - Start completed.
2021-12-08 10:34:24  INFO: Operating system name: Linux version: 5.11.0-41-generic architecture: amd64
2021-12-08 10:34:24  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Ubuntu version: 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-08 10:34:24  INFO: Memory limit heap: 962mb non-heap: 0mb
2021-12-08 10:34:24  INFO: Character encoding: UTF-8 charset: UTF-8
2021-12-08 10:34:24  INFO: Version: 4.14
2021-12-08 10:34:24  INFO: Starting server...
2021-12-08 10:34:27  INFO: jetty-10.0.6; built: 2021-06-29T15:28:56.259Z; git: 37e7731b4b142a882d73974ff3bec78d621bd674; jvm 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-08 10:34:31  INFO: Started o.t.w.@51b87df7{/,null,AVAILABLE}
2021-12-08 10:34:31  INFO: Session workerName=node0
2021-12-08 10:34:33  WARN: JAXBContext implementation could not be found. WADL feature is disabled.
2021-12-08 10:34:34  INFO: Started o.e.j.s.ServletContextHandler@be616f0{/,null,AVAILABLE}
2021-12-08 10:34:34  INFO: Started ServerConnector@37864b77{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2021-12-08 10:34:34  INFO: Started Server@2589d787{STARTING}[10.0.6,sto=0] @57379ms
2021-12-08 18:00:18  INFO: HikariPool-1 - Starting...
2021-12-08 18:00:31 ERROR: HikariPool-1 - Exception during pool initialization. - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
2021-12-08 18:00:32 ERROR: Main method error - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
Exception in thread "main" java.lang.RuntimeException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at org.traccar.Main.run(Main.java:150)
	at org.traccar.Main.main(Main.java:108)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.traccar.database.DataManager.initDatabase(DataManager.java:131)
	at org.traccar.database.DataManager.<init>(DataManager.java:90)
	at org.traccar.Context.init(Context.java:319)
	at org.traccar.Main.run(Main.java:122)
	... 1 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:898)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	... 7 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:119)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:842)
	... 16 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
	... 18 more
2021-12-08 18:00:33  INFO: HikariPool-1 - Starting...
2021-12-08 18:00:39 ERROR: HikariPool-1 - Exception during pool initialization. - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
2021-12-08 18:00:39 ERROR: Main method error - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
Exception in thread "main" java.lang.RuntimeException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at org.traccar.Main.run(Main.java:150)
	at org.traccar.Main.main(Main.java:108)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.traccar.database.DataManager.initDatabase(DataManager.java:131)
	at org.traccar.database.DataManager.<init>(DataManager.java:90)
	at org.traccar.Context.init(Context.java:319)
	at org.traccar.Main.run(Main.java:122)
	... 1 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:898)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	... 7 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:119)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:842)
	... 16 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
	... 18 more
2021-12-08 18:00:42  INFO: HikariPool-1 - Starting...
2021-12-08 18:00:46  INFO: HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@2ad48653
2021-12-08 18:00:46  INFO: HikariPool-1 - Start completed.
2021-12-08 18:00:50  INFO: Clearing database change log checksums
2021-12-08 18:00:52  INFO: Successfully acquired change log lock
2021-12-08 18:00:54  INFO: Successfully released change log lock
2021-12-08 18:00:54  INFO: Successfully acquired change log lock
2021-12-08 18:00:54  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.json.JsonChangeLogParser Unable to get public no-arg constructor
2021-12-08 18:00:54  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.yaml.YamlChangeLogParser Unable to get public no-arg constructor
2021-12-08 18:00:59  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-08 18:01:06  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-08 18:01:06  INFO: Cannot load service: liquibase.hub.HubService: Provider liquibase.hub.core.StandardHubService could not be instantiated
2021-12-08 18:01:06  INFO: Successfully released change log lock
2021-12-08 18:01:13  INFO: HikariPool-2 - Starting...
2021-12-08 18:01:13  INFO: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@472d0f4
2021-12-08 18:01:13  INFO: HikariPool-2 - Start completed.
2021-12-08 18:01:14  INFO: Operating system name: Linux version: 5.11.0-41-generic architecture: amd64
2021-12-08 18:01:14  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Ubuntu version: 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-08 18:01:14  INFO: Memory limit heap: 962mb non-heap: 0mb
2021-12-08 18:01:14  INFO: Character encoding: UTF-8 charset: UTF-8
2021-12-08 18:01:14  INFO: Version: 4.14
2021-12-08 18:01:14  INFO: Starting server...
2021-12-08 18:01:15  INFO: jetty-10.0.6; built: 2021-06-29T15:28:56.259Z; git: 37e7731b4b142a882d73974ff3bec78d621bd674; jvm 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-08 18:01:16  INFO: Started o.t.w.@5bec3e0{/,null,AVAILABLE}
2021-12-08 18:01:16  INFO: Session workerName=node0
2021-12-08 18:01:18  WARN: JAXBContext implementation could not be found. WADL feature is disabled.
2021-12-08 18:01:19  INFO: Started o.e.j.s.ServletContextHandler@eb1d475{/,null,AVAILABLE}
2021-12-08 18:01:19  INFO: Started ServerConnector@87b5b49{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2021-12-08 18:01:19  INFO: Started Server@2dc39b53{STARTING}[10.0.6,sto=0] @36955ms
2021-12-09 12:38:34  INFO: HikariPool-1 - Starting...
2021-12-09 12:38:45  INFO: HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@6bb4dd34
2021-12-09 12:38:45  INFO: HikariPool-1 - Start completed.
2021-12-09 12:38:52  INFO: Clearing database change log checksums
2021-12-09 12:38:54  INFO: Successfully acquired change log lock
2021-12-09 12:38:57  INFO: Successfully released change log lock
2021-12-09 12:38:57  INFO: Successfully acquired change log lock
2021-12-09 12:38:57  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.json.JsonChangeLogParser Unable to get public no-arg constructor
2021-12-09 12:38:58  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.yaml.YamlChangeLogParser Unable to get public no-arg constructor
2021-12-09 12:39:04  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-09 12:39:16  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-09 12:39:16  INFO: Cannot load service: liquibase.hub.HubService: Provider liquibase.hub.core.StandardHubService could not be instantiated
2021-12-09 12:39:17  INFO: Successfully released change log lock
2021-12-09 12:39:33  INFO: HikariPool-2 - Starting...
2021-12-09 12:39:33  INFO: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@4bc59b27
2021-12-09 12:39:33  INFO: HikariPool-2 - Start completed.
2021-12-09 12:39:34  INFO: Operating system name: Linux version: 5.11.0-41-generic architecture: amd64
2021-12-09 12:39:34  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Ubuntu version: 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-09 12:39:34  INFO: Memory limit heap: 962mb non-heap: 0mb
2021-12-09 12:39:34  INFO: Character encoding: UTF-8 charset: UTF-8
2021-12-09 12:39:34  INFO: Version: 4.14
2021-12-09 12:39:34  INFO: Starting server...
2021-12-09 12:39:35  INFO: jetty-10.0.6; built: 2021-06-29T15:28:56.259Z; git: 37e7731b4b142a882d73974ff3bec78d621bd674; jvm 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-09 12:39:36  INFO: Started o.t.w.@3b57dba4{/,null,AVAILABLE}
2021-12-09 12:39:36  INFO: Session workerName=node0
2021-12-09 12:39:37  WARN: JAXBContext implementation could not be found. WADL feature is disabled.
2021-12-09 12:39:38  INFO: Started o.e.j.s.ServletContextHandler@389008d1{/,null,AVAILABLE}
2021-12-09 12:39:38  INFO: Started ServerConnector@4a7a965d{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2021-12-09 12:39:38  INFO: Started Server@45037e16{STARTING}[10.0.6,sto=0] @143693ms
2021-12-10 17:44:12  INFO: HikariPool-1 - Starting...
2021-12-10 17:44:28 ERROR: HikariPool-1 - Exception during pool initialization. - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
2021-12-10 17:44:29 ERROR: Main method error - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
Exception in thread "main" java.lang.RuntimeException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at org.traccar.Main.run(Main.java:150)
	at org.traccar.Main.main(Main.java:108)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.traccar.database.DataManager.initDatabase(DataManager.java:131)
	at org.traccar.database.DataManager.<init>(DataManager.java:90)
	at org.traccar.Context.init(Context.java:319)
	at org.traccar.Main.run(Main.java:122)
	... 1 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:898)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	... 7 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:119)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:842)
	... 16 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
	... 18 more
2021-12-10 17:44:30  INFO: HikariPool-1 - Starting...
2021-12-10 17:44:34  INFO: HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@e3b3b2f
2021-12-10 17:44:34  INFO: HikariPool-1 - Start completed.
2021-12-10 17:44:37  INFO: Clearing database change log checksums
2021-12-10 17:44:38  INFO: Successfully acquired change log lock
2021-12-10 17:44:40  INFO: Successfully released change log lock
2021-12-10 17:44:40  INFO: Successfully acquired change log lock
2021-12-10 17:44:40  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.json.JsonChangeLogParser Unable to get public no-arg constructor
2021-12-10 17:44:40  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.yaml.YamlChangeLogParser Unable to get public no-arg constructor
2021-12-10 17:44:45  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-10 17:44:57  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-10 17:44:57  INFO: Cannot load service: liquibase.hub.HubService: Provider liquibase.hub.core.StandardHubService could not be instantiated
2021-12-10 17:44:57  INFO: Successfully released change log lock
2021-12-10 17:45:06  INFO: HikariPool-2 - Starting...
2021-12-10 17:45:06  INFO: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@4a50d04a
2021-12-10 17:45:06  INFO: HikariPool-2 - Start completed.
2021-12-10 17:45:07  INFO: Operating system name: Linux version: 5.11.0-41-generic architecture: amd64
2021-12-10 17:45:07  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Ubuntu version: 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-10 17:45:07  INFO: Memory limit heap: 962mb non-heap: 0mb
2021-12-10 17:45:07  INFO: Character encoding: UTF-8 charset: UTF-8
2021-12-10 17:45:07  INFO: Version: 4.14
2021-12-10 17:45:07  INFO: Starting server...
2021-12-10 17:45:07  INFO: jetty-10.0.6; built: 2021-06-29T15:28:56.259Z; git: 37e7731b4b142a882d73974ff3bec78d621bd674; jvm 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-10 17:45:08  INFO: Started o.t.w.@4d81e83a{/,null,AVAILABLE}
2021-12-10 17:45:08  INFO: Session workerName=node0
2021-12-10 17:45:10  WARN: JAXBContext implementation could not be found. WADL feature is disabled.
2021-12-10 17:45:11  INFO: Started o.e.j.s.ServletContextHandler@42b43a6{/,null,AVAILABLE}
2021-12-10 17:45:11  INFO: Started ServerConnector@7308ffff{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2021-12-10 17:45:11  INFO: Started Server@7c453c34{STARTING}[10.0.6,sto=0] @41510ms
2021-12-13 11:15:12  INFO: HikariPool-1 - Starting...
2021-12-13 11:15:24  INFO: HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@41488b16
2021-12-13 11:15:24  INFO: HikariPool-1 - Start completed.
2021-12-13 11:15:28  INFO: Clearing database change log checksums
2021-12-13 11:15:29  INFO: Successfully acquired change log lock
2021-12-13 11:15:31  INFO: Successfully released change log lock
2021-12-13 11:15:31  INFO: Successfully acquired change log lock
2021-12-13 11:15:31  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.json.JsonChangeLogParser Unable to get public no-arg constructor
2021-12-13 11:15:32  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.yaml.YamlChangeLogParser Unable to get public no-arg constructor
2021-12-13 11:15:40  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-13 11:15:48  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-13 11:15:48  INFO: Cannot load service: liquibase.hub.HubService: Provider liquibase.hub.core.StandardHubService could not be instantiated
2021-12-13 11:15:48  INFO: Successfully released change log lock
2021-12-13 11:15:56  INFO: HikariPool-2 - Starting...
2021-12-13 11:15:56  INFO: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@6b1b19cf
2021-12-13 11:15:56  INFO: HikariPool-2 - Start completed.
2021-12-13 11:15:57  INFO: Operating system name: Linux version: 5.11.0-41-generic architecture: amd64
2021-12-13 11:15:57  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Ubuntu version: 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-13 11:15:57  INFO: Memory limit heap: 962mb non-heap: 0mb
2021-12-13 11:15:57  INFO: Character encoding: UTF-8 charset: UTF-8
2021-12-13 11:15:57  INFO: Version: 4.14
2021-12-13 11:15:57  INFO: Starting server...
2021-12-13 11:15:58  INFO: jetty-10.0.6; built: 2021-06-29T15:28:56.259Z; git: 37e7731b4b142a882d73974ff3bec78d621bd674; jvm 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-13 11:15:58  INFO: Started o.t.w.@1b46392c{/,null,AVAILABLE}
2021-12-13 11:15:59  INFO: Session workerName=node0
2021-12-13 11:16:00  WARN: JAXBContext implementation could not be found. WADL feature is disabled.
2021-12-13 11:16:01  INFO: Started o.e.j.s.ServletContextHandler@846b47{/,null,AVAILABLE}
2021-12-13 11:16:01  INFO: Started ServerConnector@1de9d54{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2021-12-13 11:16:01  INFO: Started Server@37606fee{STARTING}[10.0.6,sto=0] @90212ms
2021-12-14 17:10:10  INFO: HikariPool-1 - Starting...
2021-12-14 17:10:27 ERROR: HikariPool-1 - Exception during pool initialization. - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
2021-12-14 17:10:27 ERROR: Main method error - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
Exception in thread "main" java.lang.RuntimeException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at org.traccar.Main.run(Main.java:150)
	at org.traccar.Main.main(Main.java:108)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.traccar.database.DataManager.initDatabase(DataManager.java:131)
	at org.traccar.database.DataManager.<init>(DataManager.java:90)
	at org.traccar.Context.init(Context.java:319)
	at org.traccar.Main.run(Main.java:122)
	... 1 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:898)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	... 7 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:119)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:842)
	... 16 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
	... 18 more
2021-12-14 17:10:29  INFO: HikariPool-1 - Starting...
2021-12-14 17:10:33  INFO: HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@2ad48653
2021-12-14 17:10:33  INFO: HikariPool-1 - Start completed.
2021-12-14 17:10:36  INFO: Clearing database change log checksums
2021-12-14 17:10:38  INFO: Successfully acquired change log lock
2021-12-14 17:10:39  INFO: Successfully released change log lock
2021-12-14 17:10:40  INFO: Successfully acquired change log lock
2021-12-14 17:10:40  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.json.JsonChangeLogParser Unable to get public no-arg constructor
2021-12-14 17:10:40  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.yaml.YamlChangeLogParser Unable to get public no-arg constructor
2021-12-14 17:10:43  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-14 17:10:49  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-14 17:10:49  INFO: Cannot load service: liquibase.hub.HubService: Provider liquibase.hub.core.StandardHubService could not be instantiated
2021-12-14 17:10:50  INFO: Successfully released change log lock
2021-12-14 17:10:57  INFO: HikariPool-2 - Starting...
2021-12-14 17:10:57  INFO: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@472d0f4
2021-12-14 17:10:57  INFO: HikariPool-2 - Start completed.
2021-12-14 17:10:58  INFO: Operating system name: Linux version: 5.11.0-41-generic architecture: amd64
2021-12-14 17:10:58  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Ubuntu version: 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-14 17:10:58  INFO: Memory limit heap: 962mb non-heap: 0mb
2021-12-14 17:10:58  INFO: Character encoding: UTF-8 charset: UTF-8
2021-12-14 17:10:58  INFO: Version: 4.14
2021-12-14 17:10:58  INFO: Starting server...
2021-12-14 17:10:58  INFO: jetty-10.0.6; built: 2021-06-29T15:28:56.259Z; git: 37e7731b4b142a882d73974ff3bec78d621bd674; jvm 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-14 17:10:59  INFO: Started o.t.w.@47569167{/,null,AVAILABLE}
2021-12-14 17:10:59  INFO: Session workerName=node0
2021-12-14 17:11:01  WARN: JAXBContext implementation could not be found. WADL feature is disabled.
2021-12-14 17:11:02  INFO: Started o.e.j.s.ServletContextHandler@11bfd751{/,null,AVAILABLE}
2021-12-14 17:11:02  INFO: Started ServerConnector@87b5b49{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2021-12-14 17:11:02  INFO: Started Server@6222391a{STARTING}[10.0.6,sto=0] @34107ms
2021-12-14 21:52:27  INFO: HikariPool-1 - Starting...
2021-12-14 21:52:45 ERROR: HikariPool-1 - Exception during pool initialization. - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
2021-12-14 21:52:45 ERROR: Main method error - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
Exception in thread "main" java.lang.RuntimeException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at org.traccar.Main.run(Main.java:150)
	at org.traccar.Main.main(Main.java:108)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.traccar.database.DataManager.initDatabase(DataManager.java:131)
	at org.traccar.database.DataManager.<init>(DataManager.java:90)
	at org.traccar.Context.init(Context.java:319)
	at org.traccar.Main.run(Main.java:122)
	... 1 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:898)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	... 7 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:119)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:842)
	... 16 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
	... 18 more
2021-12-14 21:52:47  INFO: HikariPool-1 - Starting...
2021-12-14 21:52:49  INFO: HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@7f2cfe3f
2021-12-14 21:52:49  INFO: HikariPool-1 - Start completed.
2021-12-14 21:52:53  INFO: Clearing database change log checksums
2021-12-14 21:52:54  INFO: Successfully acquired change log lock
2021-12-14 21:52:56  INFO: Successfully released change log lock
2021-12-14 21:52:56  INFO: Successfully acquired change log lock
2021-12-14 21:52:56  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.json.JsonChangeLogParser Unable to get public no-arg constructor
2021-12-14 21:52:56  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.yaml.YamlChangeLogParser Unable to get public no-arg constructor
2021-12-14 21:53:01  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-14 21:53:11  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-14 21:53:11  INFO: Cannot load service: liquibase.hub.HubService: Provider liquibase.hub.core.StandardHubService could not be instantiated
2021-12-14 21:53:11  INFO: Successfully released change log lock
2021-12-14 21:53:23  INFO: HikariPool-2 - Starting...
2021-12-14 21:53:23  INFO: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@4f486211
2021-12-14 21:53:23  INFO: HikariPool-2 - Start completed.
2021-12-14 21:53:25  INFO: Operating system name: Linux version: 5.11.0-41-generic architecture: amd64
2021-12-14 21:53:25  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Ubuntu version: 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-14 21:53:25  INFO: Memory limit heap: 962mb non-heap: 0mb
2021-12-14 21:53:25  INFO: Character encoding: UTF-8 charset: UTF-8
2021-12-14 21:53:25  INFO: Version: 4.14
2021-12-14 21:53:25  INFO: Starting server...
2021-12-14 21:53:26  INFO: jetty-10.0.6; built: 2021-06-29T15:28:56.259Z; git: 37e7731b4b142a882d73974ff3bec78d621bd674; jvm 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-14 21:53:29  INFO: Started o.t.w.@6b2aafbc{/,null,AVAILABLE}
2021-12-14 21:53:30  INFO: Session workerName=node0
2021-12-14 21:53:35  WARN: JAXBContext implementation could not be found. WADL feature is disabled.
2021-12-14 21:53:37  INFO: Started o.e.j.s.ServletContextHandler@22c29aa8{/,null,AVAILABLE}
2021-12-14 21:53:37  INFO: Started ServerConnector@573284a5{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2021-12-14 21:53:37  INFO: Started Server@6de43bc1{STARTING}[10.0.6,sto=0] @50136ms
2021-12-15 10:34:25  INFO: HikariPool-1 - Starting...
2021-12-15 10:34:41  INFO: HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@41488b16
2021-12-15 10:34:41  INFO: HikariPool-1 - Start completed.
2021-12-15 10:34:45  INFO: Clearing database change log checksums
2021-12-15 10:34:46  INFO: Successfully acquired change log lock
2021-12-15 10:34:48  INFO: Successfully released change log lock
2021-12-15 10:34:48  INFO: Successfully acquired change log lock
2021-12-15 10:34:48  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.json.JsonChangeLogParser Unable to get public no-arg constructor
2021-12-15 10:34:48  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.yaml.YamlChangeLogParser Unable to get public no-arg constructor
2021-12-15 10:34:53  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-15 10:35:06  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-15 10:35:06  INFO: Cannot load service: liquibase.hub.HubService: Provider liquibase.hub.core.StandardHubService could not be instantiated
2021-12-15 10:35:06  INFO: Successfully released change log lock
2021-12-15 10:35:15  INFO: HikariPool-2 - Starting...
2021-12-15 10:35:15  INFO: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@6b1b19cf
2021-12-15 10:35:15  INFO: HikariPool-2 - Start completed.
2021-12-15 10:35:17  INFO: Operating system name: Linux version: 5.11.0-41-generic architecture: amd64
2021-12-15 10:35:17  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Ubuntu version: 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-15 10:35:17  INFO: Memory limit heap: 962mb non-heap: 0mb
2021-12-15 10:35:17  INFO: Character encoding: UTF-8 charset: UTF-8
2021-12-15 10:35:17  INFO: Version: 4.14
2021-12-15 10:35:17  INFO: Starting server...
2021-12-15 10:35:17  INFO: jetty-10.0.6; built: 2021-06-29T15:28:56.259Z; git: 37e7731b4b142a882d73974ff3bec78d621bd674; jvm 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-15 10:35:19  INFO: Started o.t.w.@1eb9bf60{/,null,AVAILABLE}
2021-12-15 10:35:19  INFO: Session workerName=node0
2021-12-15 10:35:19  WARN: JAXBContext implementation could not be found. WADL feature is disabled.
2021-12-15 10:35:20  INFO: Started o.e.j.s.ServletContextHandler@3d764641{/,null,AVAILABLE}
2021-12-15 10:35:20  INFO: Started ServerConnector@1de9d54{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2021-12-15 10:35:20  INFO: Started Server@51e7589f{STARTING}[10.0.6,sto=0] @97023ms
2021-12-16 11:14:03  INFO: HikariPool-1 - Starting...
2021-12-16 11:14:17 ERROR: HikariPool-1 - Exception during pool initialization. - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
2021-12-16 11:14:17 ERROR: Main method error - Connection refused (Connection refused) - ConnectException (... < DataManager:131 < *:90 < Context:319 < Main:122 < ...)
Exception in thread "main" java.lang.RuntimeException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at org.traccar.Main.run(Main.java:150)
	at org.traccar.Main.main(Main.java:108)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.traccar.database.DataManager.initDatabase(DataManager.java:131)
	at org.traccar.database.DataManager.<init>(DataManager.java:90)
	at org.traccar.Context.init(Context.java:319)
	at org.traccar.Main.run(Main.java:122)
	... 1 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:898)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	... 7 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:119)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:842)
	... 16 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
	... 18 more
2021-12-16 11:14:19  INFO: HikariPool-1 - Starting...
2021-12-16 11:14:23  INFO: HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@18f8cd79
2021-12-16 11:14:23  INFO: HikariPool-1 - Start completed.
2021-12-16 11:14:26  INFO: Clearing database change log checksums
2021-12-16 11:14:28  INFO: Successfully acquired change log lock
2021-12-16 11:14:29  INFO: Successfully released change log lock
2021-12-16 11:14:30  INFO: Successfully acquired change log lock
2021-12-16 11:14:30  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.json.JsonChangeLogParser Unable to get public no-arg constructor
2021-12-16 11:14:30  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.yaml.YamlChangeLogParser Unable to get public no-arg constructor
2021-12-16 11:14:33  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-16 11:14:40  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-16 11:14:40  INFO: Cannot load service: liquibase.hub.HubService: Provider liquibase.hub.core.StandardHubService could not be instantiated
2021-12-16 11:14:41  INFO: Successfully released change log lock
2021-12-16 11:14:47  INFO: HikariPool-2 - Starting...
2021-12-16 11:14:47  INFO: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@5529ff44
2021-12-16 11:14:47  INFO: HikariPool-2 - Start completed.
2021-12-16 11:14:48  INFO: Operating system name: Linux version: 5.11.0-41-generic architecture: amd64
2021-12-16 11:14:48  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Ubuntu version: 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-16 11:14:48  INFO: Memory limit heap: 962mb non-heap: 0mb
2021-12-16 11:14:48  INFO: Character encoding: UTF-8 charset: UTF-8
2021-12-16 11:14:48  INFO: Version: 4.14
2021-12-16 11:14:48  INFO: Starting server...
2021-12-16 11:14:49  INFO: jetty-10.0.6; built: 2021-06-29T15:28:56.259Z; git: 37e7731b4b142a882d73974ff3bec78d621bd674; jvm 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-16 11:14:50  INFO: Started o.t.w.@751d7425{/,null,AVAILABLE}
2021-12-16 11:14:50  INFO: Session workerName=node0
2021-12-16 11:14:52  WARN: JAXBContext implementation could not be found. WADL feature is disabled.
2021-12-16 11:14:52  INFO: Started o.e.j.s.ServletContextHandler@ca2be53{/,null,AVAILABLE}
2021-12-16 11:14:52  INFO: Started ServerConnector@3b95d13c{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2021-12-16 11:14:52  INFO: Started Server@5657967b{STARTING}[10.0.6,sto=0] @33868ms
2021-12-18 13:14:52  INFO: HikariPool-1 - Starting...
2021-12-18 13:15:09  INFO: HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@41488b16
2021-12-18 13:15:09  INFO: HikariPool-1 - Start completed.
2021-12-18 13:15:15  INFO: Clearing database change log checksums
2021-12-18 13:15:16  INFO: Successfully acquired change log lock
2021-12-18 13:15:18  INFO: Successfully released change log lock
2021-12-18 13:15:18  INFO: Successfully acquired change log lock
2021-12-18 13:15:18  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.json.JsonChangeLogParser Unable to get public no-arg constructor
2021-12-18 13:15:18  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.yaml.YamlChangeLogParser Unable to get public no-arg constructor
2021-12-18 13:15:23  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-18 13:15:31  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-18 13:15:31  INFO: Cannot load service: liquibase.hub.HubService: Provider liquibase.hub.core.StandardHubService could not be instantiated
2021-12-18 13:15:31  INFO: Successfully released change log lock
2021-12-18 13:15:43  INFO: HikariPool-2 - Starting...
2021-12-18 13:15:43  INFO: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@6b1b19cf
2021-12-18 13:15:43  INFO: HikariPool-2 - Start completed.
2021-12-18 13:15:44  INFO: Operating system name: Linux version: 5.11.0-41-generic architecture: amd64
2021-12-18 13:15:44  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Ubuntu version: 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-18 13:15:44  INFO: Memory limit heap: 962mb non-heap: 0mb
2021-12-18 13:15:44  INFO: Character encoding: UTF-8 charset: UTF-8
2021-12-18 13:15:44  INFO: Version: 4.14
2021-12-18 13:15:44  INFO: Starting server...
2021-12-18 13:15:45  INFO: jetty-10.0.6; built: 2021-06-29T15:28:56.259Z; git: 37e7731b4b142a882d73974ff3bec78d621bd674; jvm 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-12-18 13:15:46  INFO: Started o.t.w.@1b46392c{/,null,AVAILABLE}
2021-12-18 13:15:46  INFO: Session workerName=node0
2021-12-18 13:15:49  WARN: JAXBContext implementation could not be found. WADL feature is disabled.
2021-12-18 13:15:49  INFO: Started o.e.j.s.ServletContextHandler@846b47{/,null,AVAILABLE}
2021-12-18 13:15:49  INFO: Started ServerConnector@1de9d54{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2021-12-18 13:15:49  INFO: Started Server@37606fee{STARTING}[10.0.6,sto=0] @136379ms
2021-12-19 11:25:18  INFO: HikariPool-1 - Starting...
2021-12-19 11:25:32  INFO: HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@2438dcd
2021-12-19 11:25:32  INFO: HikariPool-1 - Start completed.
2021-12-19 11:25:35  INFO: Clearing database change log checksums
2021-12-19 11:25:37  INFO: Successfully acquired change log lock
2021-12-19 11:25:38  INFO: Successfully released change log lock
2021-12-19 11:25:39  INFO: Successfully acquired change log lock
2021-12-19 11:25:39  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.json.JsonChangeLogParser Unable to get public no-arg constructor
2021-12-19 11:25:39  INFO: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.yaml.YamlChangeLogParser Unable to get public no-arg constructor
2021-12-19 11:25:44  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-19 11:25:57  INFO: Reading from telescope.DATABASECHANGELOG
2021-12-19 11:25:57  INFO: Cannot load service: liquibase.hub.HubService: Provider liquibase.hub.core.StandardHubService could not be instantiated
2021-12-19 11:25:57  INFO: Successfully released change log lock
2021-12-19 11:26:09  INFO: HikariPool-2 - Starting...
2021-12-19 11:26:09  INFO: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@6d672bd4
2021-12-19 11:26:09  INFO: HikariPool-2 - Start completed.
2021-12-19 11:26:15  INFO: Operating system name: Linux version: 5.11.0-43-generic architecture: amd64
2021-12-19 11:26:15  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Ubuntu version: 11.0.13+8-Ubuntu-0ubuntu1.20.04
2021-12-19 11:26:15  INFO: Memory limit heap: 962mb non-heap: 0mb
2021-12-19 11:26:15  INFO: Character encoding: UTF-8 charset: UTF-8
2021-12-19 11:26:15  INFO: Version: 4.14
2021-12-19 11:26:15  INFO: Starting server...
2021-12-19 11:26:16  INFO: jetty-10.0.6; built: 2021-06-29T15:28:56.259Z; git: 37e7731b4b142a882d73974ff3bec78d621bd674; jvm 11.0.13+8-Ubuntu-0ubuntu1.20.04
2021-12-19 11:26:18  INFO: Started o.t.w.@60deefed{/,null,AVAILABLE}
2021-12-19 11:26:18  INFO: Session workerName=node0
2021-12-19 11:26:20  WARN: JAXBContext implementation could not be found. WADL feature is disabled.
2021-12-19 11:26:21  INFO: Started o.e.j.s.ServletContextHandler@70f98f7a{/,null,AVAILABLE}
2021-12-19 11:26:21  INFO: Started ServerConnector@540b0448{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2021-12-19 11:26:21  INFO: Started Server@5657967b{STARTING}[10.0.6,sto=0] @106180ms
2021-12-19 13:24:34  WARN: HikariPool-2 - Thread starvation or clock leap detected (housekeeper delta=55s173ms77µs7ns).
2021-12-19 13:24:34  WARN: HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m1s623ms497µs527ns).
